RSS_SOURCES = [
    {"name": "Yahoo Finance", "url": "https://finance.yahoo.com/news/rssindex", "desk": "Markets", "tier": 1},
    {"name": "CNBC Markets", "url": "https://www.cnbc.com/id/15839135/device/rss/rss.html", "desk": "Markets", "tier": 1},
    {"name": "MarketWatch Top Stories", "url": "https://www.marketwatch.com/rss/topstories", "desk": "Markets", "tier": 1},
    {"name": "MarketWatch Real-Time", "url": "https://www.marketwatch.com/rss/realtimeheadlines", "desk": "Markets", "tier": 1},
    {"name": "WSJ Markets", "url": "https://feeds.a.dj.com/rss/RSSMarketsMain.xml", "desk": "Markets", "tier": 1},
    {"name": "WSJ World", "url": "https://feeds.a.dj.com/rss/RSSWorldNews.xml", "desk": "Macro", "tier": 1},
    {"name": "Financial Times", "url": "https://www.ft.com/rss/home", "desk": "Macro", "tier": 1},
    {"name": "NYT Business", "url": "https://rss.nytimes.com/services/xml/rss/nyt/Business.xml", "desk": "Business", "tier": 1},
    {"name": "BBC Business", "url": "https://feeds.bbci.co.uk/news/business/rss.xml", "desk": "Business", "tier": 1},
    {"name": "AP Business", "url": "https://apnews.com/hub/business?output=rss", "desk": "Business", "tier": 1},
    {"name": "Federal Reserve Press", "url": "https://www.federalreserve.gov/feeds/press_all.xml", "desk": "Rates", "tier": 1},
    {"name": "SEC Press Releases", "url": "https://www.sec.gov/news/pressreleases.rss", "desk": "Regulatory", "tier": 1},
    {"name": "ECB Press", "url": "https://www.ecb.europa.eu/rss/press.html", "desk": "Rates", "tier": 2},
    {"name": "Investing.com News", "url": "https://www.investing.com/rss/news.rss", "desk": "Markets", "tier": 2},
    {"name": "Nasdaq Markets", "url": "https://www.nasdaq.com/feed/rssoutbound?category=Markets", "desk": "Markets", "tier": 2},
    {"name": "PR Newswire Earnings", "url": "https://www.prnewswire.com/rss/earnings-latest-news/earnings-latest-news-list.rss", "desk": "Earnings", "tier": 3},
    {"name": "Business Wire Finance", "url": "https://feed.businesswire.com/rss/home/?rss=G1QFDERJXkJeGVtQWA==", "desk": "Company News", "tier": 3},
    {"name": "Oilprice", "url": "https://oilprice.com/rss/main", "desk": "Commodities", "tier": 2},
]

