TRADE_CANDIDATE = "TRADE_CANDIDATE"
WATCHLIST_CANDIDATE = "WATCHLIST_CANDIDATE"
BLOCKED_CANDIDATE = "BLOCKED_CANDIDATE"
DATA_BLOCKED_CANDIDATE = "DATA_BLOCKED_CANDIDATE"

SUPPORTED_CLASSIFICATIONS = {
    TRADE_CANDIDATE,
    WATCHLIST_CANDIDATE,
    BLOCKED_CANDIDATE,
    DATA_BLOCKED_CANDIDATE,
}
